# Define upstream for Load Balancing the Gateway replicas
upstream api_nodes {
    server gateway:8000;
}

server {
    listen 80;
    server_name translingo.com api.translingo.com;

    # Certbot challenge for SSL generation
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all HTTP to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name translingo.com;

    ssl_certificate /etc/letsencrypt/live/translingo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/translingo.com/privkey.pem;

    # Serve React Frontend
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 443 ssl;
    server_name api.translingo.com;

    ssl_certificate /etc/letsencrypt/live/translingo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/translingo.com/privkey.pem;

    # Route to API Gateway
    location / {
        proxy_pass http://api_nodes; # Points to the upstream block
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Increase timeout for AI models
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
    }
}